package com.app.tributum.activity.contract;

import androidx.annotation.IntDef;

@IntDef({PhotoCrop.ID_CAMERA, PhotoCrop.ID_SELECT,
        PhotoCrop.MARRIAGE_CAMERA, PhotoCrop.MARRIAGE_SELECT,
        PhotoCrop.PPS_CAMERA, PhotoCrop.PPS_SELECT,
        PhotoCrop.BACK_CAMERA, PhotoCrop.BACK_SELECT,
        PhotoCrop.BILL_CAMERA, PhotoCrop.BILL_SELECT,
        PhotoCrop.LETTER_CAMERA, PhotoCrop.LETTER_SELECT,
        PhotoCrop.DIR_1_FRONT_CAMERA, PhotoCrop.DIR_1_FRONT_SELECT,
        PhotoCrop.DIR_1_BACK_CAMERA, PhotoCrop.DIR_1_BACK_SELECT,
        PhotoCrop.DIR_1_ID_CAMERA, PhotoCrop.DIR_1_ID_SELECT,
        PhotoCrop.DIR_1_PASS_CAMERA, PhotoCrop.DIR_1_PASS_SELECT,
        PhotoCrop.DIR_2_FRONT_CAMERA, PhotoCrop.DIR_2_FRONT_SELECT,
        PhotoCrop.DIR_2_BACK_CAMERA, PhotoCrop.DIR_2_BACK_SELECT,
        PhotoCrop.DIR_2_ID_CAMERA, PhotoCrop.DIR_2_ID_SELECT,
        PhotoCrop.DIR_2_PASS_CAMERA, PhotoCrop.DIR_2_PASS_SELECT,
        PhotoCrop.DIR_3_FRONT_CAMERA, PhotoCrop.DIR_3_FRONT_SELECT,
        PhotoCrop.DIR_3_BACK_CAMERA, PhotoCrop.DIR_3_BACK_SELECT,
        PhotoCrop.DIR_3_ID_CAMERA, PhotoCrop.DIR_3_ID_SELECT,
        PhotoCrop.DIR_3_PASS_CAMERA, PhotoCrop.DIR_3_PASS_SELECT,
})
public @interface PhotoCrop {
    int ID_CAMERA = 0,
            ID_SELECT = 1,
            MARRIAGE_CAMERA = 2,
            MARRIAGE_SELECT = 3,
            PPS_CAMERA = 4,
            PPS_SELECT = 5,
            BACK_CAMERA = 6,
            BACK_SELECT = 7,
            BILL_SELECT = 8,
            BILL_CAMERA = 9,
            LETTER_SELECT = 10,
            LETTER_CAMERA = 11,
            DIR_1_FRONT_CAMERA = 12,
            DIR_1_FRONT_SELECT = 13,
            DIR_1_BACK_CAMERA = 14,
            DIR_1_BACK_SELECT = 15,
            DIR_1_ID_CAMERA = 16,
            DIR_1_ID_SELECT = 17,
            DIR_1_PASS_CAMERA = 18,
            DIR_1_PASS_SELECT = 19,
            DIR_2_FRONT_CAMERA = 20,
            DIR_2_FRONT_SELECT = 21,
            DIR_2_BACK_CAMERA = 22,
            DIR_2_BACK_SELECT = 23,
            DIR_2_ID_CAMERA = 24,
            DIR_2_ID_SELECT = 25,
            DIR_2_PASS_CAMERA = 26,
            DIR_2_PASS_SELECT = 27,
            DIR_3_FRONT_CAMERA = 28,
            DIR_3_FRONT_SELECT = 29,
            DIR_3_BACK_CAMERA = 30,
            DIR_3_BACK_SELECT = 31,
            DIR_3_ID_CAMERA = 32,
            DIR_3_ID_SELECT = 33,
            DIR_3_PASS_CAMERA = 34,
            DIR_3_PASS_SELECT = 35;
}